module.exports = {
  UNKNOWN_PACKET: "iris/unknown-packet",
  ERROR: "iris/error",
  LISTENING: "iris/listening",
  HANDSHAKE: "iris/handshake",
  PING: "iris/ping",
  PEER_CONNECTED: "iris/peer-connected",
  PEER_DISCONNECTED: "iris/peer-disconnected",
  NETWORK_INFORMATION: "iris/network-information",
  MESSAGE: "iris/message",
  PROGRESS: "iris/progress",
  REQUEST_FILES: "iris/request-files",
  RESPONSE_FILES: "iris/response-files",
  FILE: "iris/file",
  FILE_INFORMATION: "iris/file-information",
  READY_FOR_DOWNLOAD: "iris/ready-for-download",
  READY_FOR_UPLOAD: "iris/ready-for-upload",
};
